cc_library(
    name = "camera",
    srcs = ["camera.cc"],
    hdrs = ["camera.h"],
    include_prefix = "qrk",
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/glad",
        "//third_party/glm",
    ],
)

cc_library(
    name = "shader",
    srcs = ["shader.cc"],
    hdrs = ["shader.h"],
    include_prefix = "qrk",
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/glad",
        "//third_party/glm",
    ],
)
